### ISSUE TITLE
Ability to create 4 working virtual controllers?

### ISSUE THREAD

**Issue by Lintence01** [mikew/xarcade-xinput#10]
I have 2 dual x arcade sticks and cannot figure out if this is possible. Was able to create 4 virtual controllers by messing around with some numbers in the mapping file but not sure if there is an actual functioning way of doing this.

**Comment by Lintence01** [comment]
Never mind got it working, was just a bit of a mess up on my part.

**Comment by mikew** [comment]
I'm actually curious how you got this setup working. I've never tried it with 2 XArcade sticks. Did you have to change the keyboard mappings on one of the XArcade devices?

**Comment by Lintence01** [comment]
Yes remapped all buttons and it works like a charm. Only problem I have now is finding a 1 button solution to disable the virtual controllers.

**Comment by mikew** [comment]
The app is built around a REST api, so pretty much anything can control it.

Here's an example using powershell:

```ps1
# Turn off
Invoke-RestMethod -Method Post -Uri http://localhost:32123/api/keyboard/stop
Invoke-RestMethod -Method Post -Uri http://localhost:32123/api/controller/stop

# Turn On
Invoke-RestMethod -Method Post -Uri http://localhost:32123/api/keyboard/start
Invoke-RestMethod -Method Post -Uri http://localhost:32123/api/controller/start
```

**Comment by mikew** [comment]
Also, I haven't had the chance to work on it, but the ability to turn the software on / off via your controller is planned: https://github.com/mikew/xarcade-xinput/issues/9

**Comment by cor094** [comment]
> Never mind got it working, was just a bit of a mess up on my part.

Anyway you can elaborate on how you got 4 players working? I thought I could just add two more configurations and replace 0 and 1 with 2 and 3, but the program won't let me make that profile active. Thanks - Cory

**Comment by mikew** [comment]
@cor094 That means the formatting of that profile is incorrect. You'll probably see a little `x` icon in the line numbers on the left where the issue is.

Feel free to copy/paste the profile here, I'll gladly fix it up and post it back.

**Comment by cor094** [comment]
> @cor094 That means the formatting of that profile is incorrect. You'll probably see a little x icon in the line numbers on the left where the issue is.
> Feel free to copy/paste the profile here, I'll gladly fix it up and post it back.

Thank you very much for your response and offer to help! Hovering over the X icon helped me figure out what it was. I was missing a comma at the end of controller 2. It is now working! Thanks again. This program is great, has allowed me to play Street Fighter V, MKX, and NBA 2K Playgrounds 2 (with 4 players) on my arcade cabinet. Thanks!
