### ISSUE TITLE
Support for passing in mapping via command-line

### ISSUE THREAD

**Issue by leojhartiv** [mikew/xarcade-xinput#15]
Love this project that you've created.  Thank you!  I'm using it with my ultimarc ipac-enabled retroarcade to launch windows games that require controllers.  

For me to really adopt this fully, I'd want to be able to pass a mapping name when executing "XArcade XInput.exe".  I have some games that don't follow the same rules around controller mappings, so this would be a great feature.

**Comment by mikew** [comment]
Thanks for the feedback! Simple request. Is this a duplicate of your other issue https://github.com/mikew/xarcade-xinput/issues/16 ?

**Comment by leojhartiv** [comment]
Yes!  I got a 404 error when I submitted the first one and didn’t notice it
actually went through. Keep whichever one your favor. :)
