### ISSUE TITLE
Pass in mapping via CLI

### ISSUE THREAD

**Issue by leojhartiv** [mikew/xarcade-xinput#16]
Love this project that you've created.  Thank you!  I'm using it with my ultimarc ipac-enabled retroarcade to launch windows games that require controllers.  

For me to really adopt this fully, I'd want to be able to pass a mapping name when executing "XArcade XInput.exe".  I have some games that don't follow the same rules around controller mappings, so this would be a great feature.

**Comment by mikew** [comment]
closing as this was a duplicate of https://github.com/mikew/xarcade-xinput/issues/15
