### ISSUE TITLE
Disable Browser Window from Powershell

### ISSUE THREAD

**Issue by Moleburt** [mikew/xarcade-xinput#20]
Is there a way to disable the browser window from opening using powershell? I have a entire script I am running to launch my game, and Xarcade Xinput from within powershell, the only thing I can't figure out is how to stop that window from opening.

**Comment by mikew** [comment]
Running the .exe with `--skip-ui` will stop the browser from opening.

**Comment by Moleburt** [comment]
Sorry to ask probably a dumb quesiton, I'm really new at doing any scripting. Here is the line I have for launching Xarcade Xinput. I tried just adding `--skip-ui` directly after the exe and it didn't work. Not sure exactly how to add it to the powershell. 

`Write-Host "Launching XArcade_XInput"
Start-Process "D:\EmulatorStuff\xarcade-xinput\XArcade_XInput.exe" -WindowStyle Minimize`

**Comment by mikew** [comment]
Not super familiar with `Start-Process` but I think you'd want:

```powershell
Write-Host "Launching XArcade_XInput"
Start-Process "D:\EmulatorStuff\xarcade-xinput\XArcade_XInput.exe" -ArgumentList "--skip-ui" -WindowStyle Minimize
```

**Comment by Moleburt** [comment]
I feel really stupid, I had written it `Start-Process "D:\EmulatorStuff\xarcade-xinput\XArcade_XInput.exe --skip-ui"` right before I commented back. Then I sent my comment and tried `Start-Process "D:\EmulatorStuff\xarcade-xinput\XArcade_XInput.exe" --skip-ui` and it worked...after 2 days of messing with it. Thanks for your help! Your Xarcade Xinput is amazing, tried to use Virtual Controller and it does weird stuff and yours does exactly what I need!

**Comment by mikew** [comment]
That's great! I'll be closing the issue now, but don't hesitate to reach out if you run into any more issues
