### ISSUE TITLE
Stopped Working after updating windows

### ISSUE THREAD

**Issue by Moleburt** [mikew/xarcade-xinput#22]
I had this working great and updated windows and all the sudden it started acting weird. It would load but not disconnect when closed. So I uninstalled the SCP driver and tried to reinstall. I'm now getting a "Driver Installation Failed with DIFxAPI error" I have no idea why I can't reinstall the driver or what I need to do to fix it and get it working again.

**Comment by mikew** [comment]
Hm, I can remember this from a while ago (that SCP driver is a bit of a mess). I'll dig around tonight and try to get back to you this weekend.

From what I can remember, it's due to some traces being left behind.

**Comment by Moleburt** [comment]
That would make sense. I noticed every time I tried to install it my device manager would show a new unknown device. I right clicked on the unknown device and clicked install from there, it now shows the SCP driver, but the Xarcade Xinput still isn’t working right. It opens and looks right, but the system never loads the 360 controllers. I’m thinking it still has something to do with the driver though.

**Comment by Moleburt** [comment]
I was able to get the driver to install properly, I downloaded installed/uninstalled SCPToolKit, and after it uninstalled I was able to install the driver for XArcade Xinput without issue. Now the only issue I am having is when I open the app for the first time it works properly, but then it doesn't close when it exited. It still shows the controllers loaded and everytime I run the app it thinks it disconnecting the controllers instead of connecting them.

**Comment by Moleburt** [comment]
Just wanted to leave a update. I tried reinstalling windows incase something was corrupted, was able to install the driver but the issue is still the application works like it should, other than when it exits it’s not disconnecting the XBox 360 devices like it should, the system thinks they’re connected still. Not sure if there is a solution for this?

**Comment by mikew** [comment]
It's probably something in the app itself, if you use the UI to turn the program off, do they disappear? Curious to what, if any, issues this actually causes.

**Comment by Moleburt** [comment]
Yes, if I disable or enable through the UI it works like it should, just not like it did a week ago where closing the cmd window would do the same thing.

**Comment by mikew** [comment]
Interesting. I've never actually checked to see if those are cleaned up. FWIW it's just those controllers sticking around: nothing is intercepting keyboard presses, and the web server closes.

Either way, I've found a fix.

**Comment by Moleburt** [comment]
Do i need to do anything for the fix or is it going to be a new release to download? Thanks for all your help either way!

**Comment by mikew** [comment]
Yep, download the latest release from the link in the readme. To upgrade, you can either bring your existing mappings from an older installation into this one, or copy and paste everything from the new version into your older installation.
