### ISSUE TITLE
change recommended test app in readme.md

### ISSUE THREAD

**Issue by offalynne** [mikew/xarcade-xinput#39]
gamepad-tester.com has been loaded with sketchy adware and autoplay ads and is apparently advertising sale of scraped user data

suggest pointing users to https://greggman.github.io/html5-gamepad-test/ or https://apps.nektro.net/gamepad

**Comment by mikew** [comment]
Oh, gross. Thanks for the heads up!

**Comment by offalynne** [comment]
Same owner. Ads seem to have cooled down but they are still selling user data collected without solicitation: https://hardwaretester.com/gamepad/dataset

Would still suggest using an alternative if you are able.
