### ISSUE TITLE
Malwarebytes flag

### ISSUE THREAD

**Issue by deadyourinstinct** [mikew/xarcade-xinput#5]
Hey I believe I downloaded it directly from here but I ran a scan with malwarebytes because of a Windows freezing issue I am having and the install driver.exe was flagged as a Trojan.Injector. Is this normal? Should I put in the exceptions list and move on? Btw I love this thing. Makes my life way easier with the tankstick

**Comment by mikew** [comment]
It seems to be a false positive due to how the driver installation .bat file is turned into an .exe. I can look into better solutions this weekend.

If you've already installed the driver, you are safe to just delete `install driver.exe`.

**Comment by mikew** [comment]
This should be fixed now with the new Install Driver project added. If you've already installed the driver, there's no need to run this new one.
