### ISSUE TITLE
No L3/R3 in X360Buttons Enum

### ISSUE THREAD

**Issue by ccoffield93** [mikew/xarcade-xinput#60]
As shown here: 

https://github.com/mikew/xarcade-xinput/blob/d1619610b3b3829a66d4d83d4ea7a7dd2080cc21/XArcade%20XInput/ScpDriverInterface/X360Controller.cs#L132

There is no current enum value for L3/R3 on the controller. While these aren't exactly *commonly* used buttons, there's more than enough buttons to support them on the X-Arcade when in one-player mode, so I figured I would suggest adding L3 and R3 values... assuming they are mappable through the same bit-shifting interface.

**Comment by mikew** [comment]
Coincidentally, I haven't used this in a while, but dusted off my setup and booted it up tonight.

I haven't checked, but isn't that `LeftStick` and `RightStick`?

**Comment by ccoffield93** [comment]
You know, I didn't think about that-- I just figured those were related to the analog stick inputs, but you're right, it would make sense for that to be what those represent since they're digital ins.

I'll give it a try later on tonight and if that's the case, I'll close this issue myself, or report back. Thanks for maintaining such a unique and useful piece of software. The only thing about it that I would improve is easier toggling on/off, but it's so great as is.

**Comment by mikew** [comment]
Thanks! I'm glad it's still handy after all these years.

And yeah, dunno when I'll get around to it but the next feature I was working on was allowing users to specify multi-button shortcuts, along with the ability to map to custom actions like "toggle"

**Comment by ccoffield93** [comment]
You got a Kofi or similar where you accept donations? I'd love to toss a few bucks at you to say I appreciate your contributions to the open source gaming community.

**Comment by mikew** [comment]
> You got a Kofi or similar where you accept donations? I'd love to toss a few bucks at you to say I appreciate your contributions to the open source gaming community.

Really appreciate it! I just threw this together: https://ko-fi.com/mikewhy

Love the use of arcade controls for vampire survivor clones with arcade controls, seems like a perfect match.
