### ISSUE TITLE
Intercepts Main Keyboard

### ISSUE THREAD

**Issue by alecazam** [mikew/xarcade-xinput#8]
First off, this is a great idea and easy way to remap the keyboard.  The issue that I found is that even my main keyboard was getting remapped.  This meant several keys no longer worked, and I couldn't type urls or passwords to log into the machine.  Fortunately, I had the web config page off and was able to disable the plugin.  Can the keyboard id be checked, and only intercept on the Xarcade "keyboard" in the code?

**Comment by mikew** [comment]
Not with the library currently being used to intercept key presses.

Plus I'd rather not go to specific IDs, I think that would hamper the usefulness of this tool, as other sticks that send keyboard events now have to be added and built, and would add constant catch-up to new boards being produced.
